Aviator/Models/PreFlight.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Aviator.Models
{
    public class PreFlight
    {
        [Key]
        public int PreFlightId { get; set; }

        [ForeignKey("FlightId")]
        public int FlightIdentification { get; set; }
        public virtual Flight FlightId { get; set; }


        [Display(Name = "Starting Engine Hours")]
        public double StartingEngineHours { get; set; }
        [Display(Name = "Starting Total Hours")]
        public double StartingHobbsHours { get; set; }
        [Display(Name = "Oil Level")]
        public double StartingOilLevel { get; set; }
        [Display(Name = "Oil Added")]
        public double AmountOilAdded { get; set; }
        [Display(Name = "Maintenance Flight")]
        public bool MaintenanceFlight { get; set; }
    }
}

Aviator/Models/PreFlightViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Aviator.Models
{
    public class PreFlightViewModel
    {
        public virtual Flight FlightModel { get; set; }
        public virtual PreFlight PreFlightModel { get; set; }
    }
}

Aviator/Controllers/PreFlightsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Aviator.Models;

namespace Aviator.Controllers
{
    public class PreFlightsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult PreFlight()
        {
            
            List<Flight> ListOfFlights = db.Flights.ToList();
            List<PostFlight> LastFlightValues = db.PostFlights.ToList();
    
            PreFlight newFlight = new PreFlight();
            var FlightNumber = ListOfFlights[ListOfFlights.Count - 1].FlightId;
            //var LastEntryEngineHours = 200.0;
            //var LastEntryHobbsHours = 450.6;
            var LastEntryEngineHours = LastFlightValues[LastFlightValues.Count - 1].EndingEngineHours;
            var LastEntryHobbsHours = LastFlightValues[LastFlightValues.Count - 1].EndingHobbsHours;
            newFlight.FlightIdentification = FlightNumber;
            newFlight.StartingEngineHours = LastEntryEngineHours;
            newFlight.StartingHobbsHours = LastEntryHobbsHours;
            return View(newFlight);
        } 

        [HttpPost]
        public ActionResult PreFlight([Bind(Include = "PreFlightId,FlightIdentification,StartingEngineHours,StartingHobbsHours,StartingOilLevel,AmountOilAdded,MaintenanceFlight")] PreFlight preFlight)
        {
            db.PreFlights.Add(preFlight);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        // GET: PreFlights
        public ActionResult Index()
        {
            var preFlights = db.PreFlights.Include(p => p.FlightId);
            return View(preFlights.ToList());
        }

        // GET: PreFlights/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PreFlight preFlight = db.PreFlights.Find(id);
            if (preFlight == null)
            {
                return HttpNotFound();
            }
            return View(preFlight);
        }

        // GET: PreFlights/Create
        public ActionResult Create()
        {
            ViewBag.Flight = new SelectList(db.Flights, "FlightId", "Destination");
            return View();
        }

        // POST: PreFlights/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PreFlightId,Flight,StartingEngineHours,StartingHobbsHours,StartingOilLevel,AmountOilAdded,MaintenanceFlight")] PreFlight preFlight)
        {
            if (ModelState.IsValid)
            {
                db.PreFlights.Add(preFlight);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Flight = new SelectList(db.Flights, "FlightId", "Destination", preFlight.FlightIdentification);
            return View(preFlight);
        }

        // GET: PreFlights/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PreFlight preFlight = db.PreFlights.Find(id);
            if (preFlight == null)
            {
                return HttpNotFound();
            }
            ViewBag.Flight = new SelectList(db.Flights, "FlightId", "Destination", preFlight.FlightIdentification);
            return View(preFlight);
        }

        // POST: PreFlights/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PreFlightId,Flight,StartingEngineHours,StartingHobbsHours,StartingOilLevel,AmountOilAdded,MaintenanceFlight")] PreFlight preFlight)
        {
            if (ModelState.IsValid)
            {
                db.Entry(preFlight).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Flight = new SelectList(db.Flights, "FlightId", "Destination", preFlight.FlightIdentification);
            return View(preFlight);
        }

        // GET: PreFlights/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PreFlight preFlight = db.PreFlights.Find(id);
            if (preFlight == null)
            {
                return HttpNotFound();
            }
            return View(preFlight);
        }

        // POST: PreFlights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PreFlight preFlight = db.PreFlights.Find(id);
            db.PreFlights.Remove(preFlight);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aviator/Views/PreFlights/Create.cshtml
@model Aviator.Models.PreFlight

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PreFlight</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Flight, "Flight", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Flight", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Flight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartngEngineHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartngEngineHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartngEngineHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartingHobbsHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartingHobbsHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartingHobbsHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartingOilLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartingOilLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartingOilLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AmountOilAdded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmountOilAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AmountOilAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaintenanceFlight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.MaintenanceFlight)
                    @Html.ValidationMessageFor(model => model.MaintenanceFlight, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aviator/Views/PreFlights/Delete.cshtml
@model Aviator.Models.PreFlight

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PreFlight</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FlightId.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightId.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartngEngineHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartngEngineHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartingHobbsHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartingHobbsHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartingOilLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartingOilLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountOilAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountOilAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaintenanceFlight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaintenanceFlight)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Aviator/Views/PreFlights/Details.cshtml
@model Aviator.Models.PreFlight

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PreFlight</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FlightId.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightId.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartngEngineHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartngEngineHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartingHobbsHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartingHobbsHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartingOilLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartingOilLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountOilAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountOilAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaintenanceFlight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaintenanceFlight)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PreFlightId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Aviator/Views/PreFlights/Edit.cshtml
@model Aviator.Models.PreFlight

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PreFlight</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PreFlightId)

        <div class="form-group">
            @Html.LabelFor(model => model.Flight, "Flight", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Flight", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Flight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartngEngineHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartngEngineHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartngEngineHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartingHobbsHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartingHobbsHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartingHobbsHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartingOilLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartingOilLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartingOilLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AmountOilAdded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmountOilAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AmountOilAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaintenanceFlight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.MaintenanceFlight)
                    @Html.ValidationMessageFor(model => model.MaintenanceFlight, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aviator/Views/PreFlights/Index.cshtml
@model IEnumerable<Aviator.Models.PreFlight>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FlightId.Destination)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartingEngineHours)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartingHobbsHours)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartingOilLevel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AmountOilAdded)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaintenanceFlight)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FlightId.Destination)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartingEngineHours)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartingHobbsHours)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartingOilLevel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AmountOilAdded)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaintenanceFlight)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PreFlightId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PreFlightId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PreFlightId })
        </td>
    </tr>
}

</table>

Aviator/Views/PreFlights/PreFlight.cshtml
@model Aviator.Models.PreFlight
@{
    ViewBag.Title = "PreFlight";
}

<h2>Pre-Flight</h2>

@using (Html.BeginForm("PreFlight", "PreFlights", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{

    @Html.AntiForgeryToken()


    <h4>Complete before take off.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    @Html.HiddenFor(m => m.FlightIdentification)
    @Html.HiddenFor(m => m.PreFlightId)

    <div class="form-group">
        @Html.LabelFor(m => m.StartingEngineHours, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.StartingEngineHours, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.StartingHobbsHours, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.StartingHobbsHours, new { @class = "form-control" })
        </div>
    </div>

    List<SelectListItem> preListItems = new List<SelectListItem>();
    preListItems.Add(new SelectListItem
    {
        Text = "6.0",
        Value = "6.0"
    });
    preListItems.Add(new SelectListItem
    {
        Text = "6.5",
        Value = "6.5"
    });
    preListItems.Add(new SelectListItem
    {
        Text = "7.0",
        Value = "7.0"
    });
    preListItems.Add(new SelectListItem
    {
        Text = "7.5",
        Value = "7.5"
    });
    preListItems.Add(new SelectListItem
    {
        Text = "8.0",
        Value = "8.0"
    });
    preListItems.Add(new SelectListItem
    {
        Text = "8.5",
        Value = "8.5"
    });
    preListItems.Add(new SelectListItem
    {
        Text = "9.0",
        Value = "9.0"
    });
    preListItems.Add(new SelectListItem
    {
        Text = "9.5",
        Value = "9.5"
    });
    preListItems.Add(new SelectListItem
    {
        Text = "10.0",
        Value = "10.0"
    });
    preListItems.Add(new SelectListItem
    {
        Text = "10.5",
        Value = "10.5"
    });
    preListItems.Add(new SelectListItem
    {
        Text = "11.0",
        Value = "11.0"
    });


    <div class="form-group">
        @Html.LabelFor(m => m.StartingOilLevel, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.StartingOilLevel, preListItems, new { @class = "form-control" })
        </div>
    </div>


    List<SelectListItem> addingOilList = new List<SelectListItem>();

    addingOilList.Add(new SelectListItem
    {
        Text = "0.0",
        Value = "0.0"
    });
    addingOilList.Add(new SelectListItem
    {
        Text = "0.5",
        Value = "0.5"
    });
    addingOilList.Add(new SelectListItem
    {
        Text = "1.0",
        Value = "1.0"
    });
    addingOilList.Add(new SelectListItem
    {
        Text = "1.5",
        Value = "1.5"
    });
    addingOilList.Add(new SelectListItem
    {
        Text = "2.0",
        Value = "2.0"
    });
    <div class="form-group">
        @Html.LabelFor(m => m.AmountOilAdded, new { @class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.AmountOilAdded, addingOilList, "------Select amount added--------", new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(m => m.MaintenanceFlight, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.RadioButtonFor(m => m.MaintenanceFlight, true,  new { @Id = "Yes" })
            <label for="Yes">Yes</label>
            @Html.RadioButtonFor(m => m.MaintenanceFlight, false, new { @Id = "No" })
            <label for="No">No</label>

        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Complete" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}